#!/usr/bin/env python3
"""Synchronise Google Scholar publications into Wowchemy content files."""

from __future__ import annotations

import argparse
import datetime as dt
import re
import shutil
from pathlib import Path
from typing import Any

import yaml
from scholarly import scholarly


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Sync Google Scholar publications to Hugo/Wowchemy")
    parser.add_argument(
        "--config",
        default="scripts/scholar-sync.yaml",
        help="Path to sync configuration YAML file",
    )
    return parser.parse_args()


def load_config(config_path: Path) -> dict[str, Any]:
    with config_path.open("r", encoding="utf-8") as handle:
        config = yaml.safe_load(handle)

    if not isinstance(config, dict):
        raise ValueError("Config must be a YAML mapping")

    return config


def slugify(value: str) -> str:
    clean = value.lower().strip()
    clean = re.sub(r"[^a-z0-9]+", "-", clean)
    clean = re.sub(r"-{2,}", "-", clean)
    return clean.strip("-")


def classify_publication_type(venue: str) -> str:
    venue_lower = venue.lower()
    journal_markers = ["journal", "transactions", "letters", "access", "review"]
    conference_markers = ["conference", "symposium", "workshop", "proceedings", "ieee ic", "ifac"]
    preprint_markers = ["arxiv", "preprint", "working paper"]

    if any(marker in venue_lower for marker in preprint_markers):
        return "3"

    if any(marker in venue_lower for marker in journal_markers):
        return "2"

    if any(marker in venue_lower for marker in conference_markers):
        return "1"

    return "0"


def fetch_author_publications(user_id: str) -> list[dict[str, Any]]:
    author = scholarly.search_author_id(user_id)
    if author is None:
        raise ValueError(f"Could not find Google Scholar profile for user_id={user_id}")

    author = scholarly.fill(author, sections=["publications"])
    publications = author.get("publications", [])
    filled: list[dict[str, Any]] = []

    for publication in publications:
        try:
            filled.append(scholarly.fill(publication))
        except Exception as exc:  # noqa: BLE001
            print(f"Skipping publication due to fetch error: {exc}")

    return filled


def build_front_matter(
    bib: dict[str, Any],
    venue: str,
    publication_type: str,
    featured: bool,
    include_citation_count_in_summary: bool,
    citation_count: int,
    pub_url: str,
) -> dict[str, Any]:
    title = bib.get("title", "Untitled publication")
    authors_raw = bib.get("author", "")
    authors = [name.strip() for name in authors_raw.split(" and ") if name.strip()]

    year_value = str(bib.get("pub_year") or bib.get("year") or dt.datetime.now().year)
    year_match = re.search(r"\d{4}", year_value)
    year = year_match.group(0) if year_match else str(dt.datetime.now().year)
    timestamp = f"{year}-01-01T00:00:00Z"

    doi = bib.get("doi", "")
    abstract = bib.get("abstract", "")

    publication = f"In *{venue}*" if venue else ""

    summary = f"Google Scholar cites: {citation_count}" if include_citation_count_in_summary else ""

    front_matter: dict[str, Any] = {
        "title": title,
        "authors": authors,
        "date": timestamp,
        "doi": doi,
        "publishDate": timestamp,
        "publication_types": [publication_type],
        "publication": publication,
        "abstract": abstract,
        "summary": summary,
        "featured": featured,
        "tags": ["google-scholar"],
        "url_pdf": bib.get("eprint_url", ""),
    }

    return front_matter


def render_publication_content(front_matter: dict[str, Any], source_url: str) -> str:
    content_parts = [
        "---\n",
        yaml.safe_dump(front_matter, sort_keys=False, allow_unicode=True),
        "---\n\n",
        "<!-- Auto-generated by scripts/sync_google_scholar.py. -->\n",
    ]

    if source_url:
        content_parts.append(f"Source: [{source_url}]({source_url})\n")

    return "".join(content_parts)


def write_if_changed(target_file: Path, content: str) -> bool:
    if target_file.exists():
        existing_content = target_file.read_text(encoding="utf-8")
        if existing_content == content:
            return False

    target_file.write_text(content, encoding="utf-8")
    return True


def remove_stale_entries(output_dir: Path, managed_slug_prefix: str, active_slugs: set[str]) -> None:
    for path in output_dir.iterdir():
        if not path.is_dir():
            continue
        if path.name == "_index.md":
            continue
        if not path.name.startswith(managed_slug_prefix):
            continue
        if path.name in active_slugs:
            continue

        shutil.rmtree(path)
        print(f"Removed stale entry: {path}")


def sync(config: dict[str, Any], config_path: Path) -> None:
    scholar_config = config.get("scholar", {})
    site_config = config.get("site", {})
    sync_config = config.get("sync", {})

    user_id = scholar_config.get("user_id")
    if not user_id:
        raise ValueError("Missing 'scholar.user_id' in config")

    root_dir = config_path.resolve().parent.parent
    output_dir = root_dir / site_config.get("output_dir", "content/publication")
    managed_slug_prefix = site_config.get("managed_slug_prefix", "scholar-")
    max_publications = int(site_config.get("max_publications", 50))
    default_featured = bool(site_config.get("featured", False))
    include_citation_count_in_summary = bool(site_config.get("include_citation_count_in_summary", True))

    remove_stale = bool(sync_config.get("remove_stale_managed_entries", True))
    dry_run = bool(sync_config.get("dry_run", False))

    output_dir.mkdir(parents=True, exist_ok=True)

    publications = fetch_author_publications(user_id)
    publications.sort(
        key=lambda p: int(str(p.get("bib", {}).get("pub_year", "0")).split("-")[0] or 0),
        reverse=True,
    )
    selected = publications[:max_publications]

    active_slugs: set[str] = set()
    created_count = 0
    updated_count = 0
    skipped_count = 0

    for publication in selected:
        bib = publication.get("bib", {})
        title = bib.get("title", "")
        if not title:
            continue

        venue = bib.get("venue", "") or bib.get("journal", "")
        publication_type = classify_publication_type(venue)

        author_pub_id = publication.get("author_pub_id", "")
        slug_base = slugify(f"{title}-{author_pub_id}" if author_pub_id else title)
        if not slug_base:
            continue

        slug = f"{managed_slug_prefix}{slug_base}"
        active_slugs.add(slug)

        publication_dir = output_dir / slug
        publication_file = publication_dir / "index.md"

        pub_url = publication.get("pub_url", "")
        citation_count = int(publication.get("num_citations", 0) or 0)

        front_matter = build_front_matter(
            bib=bib,
            venue=venue,
            publication_type=publication_type,
            featured=default_featured,
            include_citation_count_in_summary=include_citation_count_in_summary,
            citation_count=citation_count,
            pub_url=pub_url,
        )

        if dry_run:
            print(f"Would write: {publication_file}")
            continue

        publication_dir.mkdir(parents=True, exist_ok=True)
        content = render_publication_content(front_matter, pub_url)
        file_existed = publication_file.exists()
        changed = write_if_changed(publication_file, content)

        if changed and file_existed:
            updated_count += 1
            print(f"Updated: {publication_file}")
        elif changed and not file_existed:
            created_count += 1
            print(f"Created: {publication_file}")
        else:
            skipped_count += 1
            print(f"Unchanged: {publication_file}")

    if remove_stale and not dry_run:
        remove_stale_entries(output_dir, managed_slug_prefix, active_slugs)

    if not dry_run:
        print(
            "Summary: "
            f"created={created_count}, "
            f"updated={updated_count}, "
            f"unchanged={skipped_count}"
        )


def main() -> None:
    args = parse_args()
    config_path = Path(args.config)

    if not config_path.exists():
        raise FileNotFoundError(f"Config file not found: {config_path}")

    config = load_config(config_path)
    sync(config, config_path)


if __name__ == "__main__":
    main()
